config/routes.rb
Rails.application.routes.draw do
  resources :validforms

   root 'validforms#index'

end

app/models/validform.rb
class Validform < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/validforms_controller.rb
class ValidformsController < ApplicationController
  before_action :set_validform, only: [:show, :edit, :update, :destroy]

  # GET /validforms
  # GET /validforms.json
  def index
    @validforms = Validform.all
  end

  # GET /validforms/1
  # GET /validforms/1.json
  def show
  end

  # GET /validforms/new
  def new
    @validform = Validform.new
  end

  # GET /validforms/1/edit
  def edit
  end

  # POST /validforms
  # POST /validforms.json
  def create
    @validform = Validform.new(validform_params)

    respond_to do |format|
      if @validform.save
        format.html { redirect_to @validform, notice: 'Validform was successfully created.' }
        format.json { render :show, status: :created, location: @validform }
      else
        format.html { render :new }
        format.json { render json: @validform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /validforms/1
  # PATCH/PUT /validforms/1.json
  def update
    respond_to do |format|
      if @validform.update(validform_params)
        format.html { redirect_to @validform, notice: 'Validform was successfully updated.' }
        format.json { render :show, status: :ok, location: @validform }
      else
        format.html { render :edit }
        format.json { render json: @validform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validforms/1
  # DELETE /validforms/1.json
  def destroy
    @validform.destroy
    respond_to do |format|
      format.html { redirect_to validforms_url, notice: 'Validform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validform
      @validform = Validform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def validform_params
      params.require(:validform).permit(:Username, :Password, :DateofBirth, :Email, :Phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/validforms_helper.rb
module ValidformsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vform</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/validforms/_form.html.erb
<%= form_for(@validform) do |f| %>
  <% if @validform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@validform.errors.count, "error") %> prohibited this validform from being saved:</h2>

      <ul>
      <% @validform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="view">
  <div class="field">
    <%= f.label :Username %><br>
    <%= f.text_field :Username, :required => true  %>
  </div>
  <div class="field">
    <%= f.label :Password %><br>
    <%= f.text_field :Password, :required => true, :type => :password  %>
  </div>
  <div class="field">
    <%= f.label :DateofBirth %><br>
    <%= f.text_field :DateofBirth, :required => true  %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.text_field :Email, :required => true  %>
  </div>
  <div class="field">
    <%= f.label :Phone %><br>
    <%= f.text_field :Phone, :required => true  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/validforms/edit.html.erb
<h1>Editing validform</h1>

<%= render 'form' %>

<%= link_to 'Show', @validform %> |
<%= link_to 'Back', validforms_path %>

app/views/validforms/index.html.erb
<h1>Listing validforms</h1>
<div class="main">
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Dateofbirth</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @validforms.each do |validform| %>
      <tr>
        <td><%= validform.Username %></td>
        <td><%= validform.Password %></td>
        <td><%= validform.DateofBirth %></td>
        <td><%= validform.Email %></td>
        <td><%= validform.Phone %></td>
        <td><%= link_to 'Show', validform %></td>
        <td><%= link_to 'Edit', edit_validform_path(validform) %></td>
        <td><%= link_to 'Destroy', validform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Validform', new_validform_path %>
</div>

app/views/validforms/new.html.erb
<h1>New validform</h1>

<%= render 'form' %>

<%= link_to 'Back', validforms_path %>

app/views/validforms/show.html.erb
<div class="display">
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @validform.Username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @validform.Password %>
</p>

<p>
  <strong>Dateofbirth:</strong>
  <%= @validform.DateofBirth %>
</p>

<p>
  <strong>Email:</strong>
  <%= @validform.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @validform.Phone %>
</p>


<%= link_to 'Back', validforms_path %>
</div>